name: CI
on:
  pull_request: {}
  push: {}

jobs:
  linux:
    runs-on: ${{ matrix.PYTHON.OS || 'ubuntu-22.04' }}
    strategy:
      matrix:
        PYTHON:
          - {VERSION: "3.9", TOXENV: "py39-randomorder"}

    name: "${{ matrix.PYTHON.TOXENV }}"
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON.VERSION }}
      - run: python -m pip install tox coverage
      - run: tox -v -- --randomly-seed=861767045
        env:
          TOXENV: ${{ matrix.PYTHON.TOXENV }}
      - name: Upload coverage
        run: |
          curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash
          bash codecov.sh -n "tox -e ${{ matrix.PYTHON.TOXENV }}"

  linux-docker:
    runs-on: ubuntu-latest
    container: ghcr.io/pyca/cryptography-runner-${{ matrix.TEST.CONTAINER }}
    strategy:
      matrix:
        TEST:
          - {CONTAINER: "ubuntu-bionic", TOXENV: "py36"}
          # cryptographyMain used since there's no wheel
          - {CONTAINER: "ubuntu-rolling", TOXENV: "py310-cryptographyMain"}
    name: "${{ matrix.TEST.TOXENV }} on ${{ matrix.TEST.CONTAINER }}"
    steps:
      - uses: actions/checkout@v3
      - run: /venv/bin/pip install tox
      - run: /venv/bin/tox -v
        env:
          TOXENV: ${{ matrix.TEST.TOXENV }}
          RUSTUP_HOME: /root/.rustup
      - name: Upload coverage
        run: |
          curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash
          bash codecov.sh -n "tox -e ${{ matrix.TEST.TOXENV }} on ${{ matrix.TEST.CONTAINER }}"
